[package]
name = "qt_generator"
version = "0.2.0"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
license = "MIT"
description = "Generator of Rust-Qt crates"
repository = "https://github.com/rust-qt/cpp_to_rust/tree/master/qt_generator/qt_generator"

[dependencies]
cpp_to_rust_generator = { version = "0.2.0", path = "../../cpp_to_rust/cpp_to_rust_generator" }
qt_generator_common = { version = "0.2.3", path = "../qt_generator_common" }

clap = "2.23.1"    # command line args parsing
regex = "1.0"
rusqlite = "0.14"
libflate = "0.1"
select = "0.4.2"    # html parsing
